apiVersion: v1
kind: Service 
metadata:
  name: myapp2-nodeport-service
  namespace: webapp2
spec:
  type: NodePort # ClusterIp, # NodePort 
  selector:
    app: myapp2
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 31200 # Node Port